# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{owasp-esapi-ruby}
  s.version = "0.30.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Owasp Esapi Ruby core\n---------------------\n\n* Paolo Perego <thesp0nge@owasp.org>\n* Sal Scotto <sal.scotto@gmail.com>"]
  s.date = %q{2011-03-09}
  s.description = %q{= The Owasp ESAPI Ruby project

== Introduction

The Owasp ESAPI Ruby is a port for outstanding release quality Owasp ESAPI
project to the Ruby programming language. 

Ruby is now a famous programming language due to its Rails framework developed by David Heinemeier Hansson (http://twitter.com/dhh) that simplify the creation of a web application using a convention over configuration approach to simplify programmers' life.

Despite Rails diffusion, there are a lot of Web framework out there that allow people to write web apps in Ruby (merb, sinatra, vintage) [http://accidentaltechnologist.com/ruby/10-alternative-ruby-web-frameworks/]. Owasp Esapi Ruby wants to bring all Ruby deevelopers a gem full of Secure APIs they can use whatever the framework they choose.

== Why supporting only Ruby 1.9.2 and beyond?

The OWASP Esapi Ruby gem will require at least version 1.9.2 of Ruby interpreter to make sure to have full advantages of the newer language APIs.

In particular version 1.9.2 introduces radical changes in the following areas:

=== Regular expression engine
(to be written)

=== UTF-8 support
Unicode support in 1.9.2 is much better and provides better support for character set encoding/decoding
* All strings have an additional chunk of info attached: Encoding
* String#size takes encoding into account – returns the encoded character count
* You can get the raw datasize
* Indexed access is by encoded data – characters, not bytes
* You can change encoding by force but it doesn’t convert the data

=== Dates and Time
From "Programming Ruby 1.9"

"As of Ruby 1.9.2, the range of dates that can be represented is no longer limited by the under- lying operating system’s time representation (so there’s no year 2038 problem). As a result, the year passed to the methods gm, local, new, mktime, and utc must now include the century—a year of 90 now represents 90 and not 1990."

== Roadmap

Please see ChangeLog file. 

== Note on Patches/Pull Requests
 
* Fork the project.
* Create documentation with rake yard task
* Make your feature addition or bug fix.
* Add tests for it. This is important so I don't break it in a
  future version unintentionally.
* Commit, do not mess with rakefile, version, or history.
  (if you want to have your own version, that is fine but bump version in a commit by itself I can ignore when I pull)
* Send me a pull request. Bonus points for topic branches.

== Copyright

Copyright (c) 2011 the OWASP Foundation. See LICENSE for details.
}
  s.email = %q{thesp0nge@owasp.org}
  s.extra_rdoc_files = [
    "ChangeLog",
    "LICENSE",
    "README"
  ]
  s.files = [
    ".document",
    "AUTHORS",
    "ChangeLog",
    "ISSUES",
    "LICENSE",
    "README",
    "Rakefile",
    "VERSION",
    "lib/codec/base_codec.rb",
    "lib/codec/css_codec.rb",
    "lib/codec/encoder.rb",
    "lib/codec/html_codec.rb",
    "lib/codec/javascript_codec.rb",
    "lib/codec/mysql_codec.rb",
    "lib/codec/oracle_codec.rb",
    "lib/codec/os_codec.rb",
    "lib/codec/percent_codec.rb",
    "lib/codec/pushable_string.rb",
    "lib/codec/vbscript_codec.rb",
    "lib/codec/xml_codec.rb",
    "lib/esapi.rb",
    "lib/exceptions.rb",
    "lib/executor.rb",
    "lib/owasp-esapi-ruby.rb",
    "lib/sanitizer/xss.rb",
    "lib/validator/base_rule.rb",
    "lib/validator/date_rule.rb",
    "lib/validator/email.rb",
    "lib/validator/float_rule.rb",
    "lib/validator/generic_validator.rb",
    "lib/validator/integer_rule.rb",
    "lib/validator/string_rule.rb",
    "lib/validator/validator_error_list.rb",
    "lib/validator/zipcode.rb",
    "spec/codec/css_codec_spec.rb",
    "spec/codec/html_codec_spec.rb",
    "spec/codec/javascript_codec_spec.rb",
    "spec/codec/mysql_codec_spec.rb",
    "spec/codec/oracle_codec_spec.rb",
    "spec/codec/os_codec_spec.rb",
    "spec/codec/percent_codec_spec.rb",
    "spec/codec/vbcript_codec_spec.rb",
    "spec/codec/xml_codec_spec.rb",
    "spec/owasp_esapi_encoder_spec.rb",
    "spec/owasp_esapi_executor_spec.rb",
    "spec/owasp_esapi_ruby_email_validator_spec.rb",
    "spec/owasp_esapi_ruby_xss_sanitizer_spec.rb",
    "spec/owasp_esapi_ruby_zipcode_validator_spec.rb",
    "spec/spec_helper.rb",
    "spec/validator/base_rule_spec.rb",
    "spec/validator/date_rule_spec.rb",
    "spec/validator/float_rule_spec.rb",
    "spec/validator/integer_rule_spec.rb",
    "spec/validator/string_rule_spec.rb",
    "spec/validator_skeleton.rb"
  ]
  s.homepage = %q{http://github.com/thesp0nge/owasp-esapi-ruby}
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.9.2")
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Owasp Enterprise Security APIs for Ruby language}
  s.test_files = [
    "spec/codec/css_codec_spec.rb",
    "spec/codec/html_codec_spec.rb",
    "spec/codec/javascript_codec_spec.rb",
    "spec/codec/mysql_codec_spec.rb",
    "spec/codec/oracle_codec_spec.rb",
    "spec/codec/os_codec_spec.rb",
    "spec/codec/percent_codec_spec.rb",
    "spec/codec/vbcript_codec_spec.rb",
    "spec/codec/xml_codec_spec.rb",
    "spec/owasp_esapi_encoder_spec.rb",
    "spec/owasp_esapi_executor_spec.rb",
    "spec/owasp_esapi_ruby_email_validator_spec.rb",
    "spec/owasp_esapi_ruby_xss_sanitizer_spec.rb",
    "spec/owasp_esapi_ruby_zipcode_validator_spec.rb",
    "spec/spec_helper.rb",
    "spec/validator/base_rule_spec.rb",
    "spec/validator/date_rule_spec.rb",
    "spec/validator/float_rule_spec.rb",
    "spec/validator/integer_rule_spec.rb",
    "spec/validator/string_rule_spec.rb",
    "spec/validator_skeleton.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<nokogiri>, [">= 1.4.4"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.4.4"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.4"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.4"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.4"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.4"])
  end
end

